# Generated by Django 4.1.1 on 2022-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("work", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
